version: "3.7"
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ghom&รงรง!
      MYSQL_DATABASE: docker
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - "./apps/my-symfony-app/public/:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
