<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO8EGhLe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO8EGhLe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO8EGhLe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO8EGhLe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO8EGhLe\App_KernelDevDebugContainer([
    'container.build_hash' => 'O8EGhLe',
    'container.build_id' => 'dbbf4bcc',
    'container.build_time' => 1579012033,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO8EGhLe');
